### ISSUE TITLE
Add phone & email in header & footer

### ISSUE THREAD

**Issue by 7yl4r** [peach-palm-admin/peach-palm-admin.github.io#13]

**Comment by LaurenPeachPalmAdmin** [comment]
Change header to add email and phone number at top
maybe put company motto/lingo?

**Comment by LaurenPeachPalmAdmin** [comment]
email and phone # i header same or similar font as header font and color

**Comment by LaurenPeachPalmAdmin** [comment]
I love it! Thank you so much.
